--目标表：DWA_A_D/M_PRO_MB_USER、DWA_A_D/M_PRO_CB_USER

--中间表 语音MID_M_MB_VOICE_S
INSERT INTO MID_M_MB_VOICE_S

SELECT
MONTH_ID,DEVICE_NUMBER,
sum(CASE WHEN TOTAL_FEE > 0 THEN CALL_DURATION
ELSE 0 END) AS VOICE_OUT,
SUM(CDR_NUMS) AS CALL_TIMES,
sum(CASE WHEN CALL_TYPE = '01' THEN CDR_NUMS
ELSE 0 END) AS CALLING_TIMES
FROM
DWA.DWA_S_M_USE_MB_VOICE_S
WHERE
MONTH_ID = '201801'
GROUP BY
MONTH_ID,DEVICE_NUMBER;


--中间表 语音MID_M_CB_VOICE_S
INSERT INTO MID_M_CB_VOICE_S

SELECT
MONTH_ID,DEVICE_NUMBER,
sum(CASE WHEN TOTAL_FEE > 0 THEN CALL_DURATION
ELSE 0 END) / 60 AS VOICE_OUT,
SUM(CDR_NUMS) AS CALL_TIMES,
sum(CASE WHEN CALL_TYPE = '01' THEN CDR_NUMS
ELSE 0 END) AS CALLING_TIMES
FROM
DWA.DWA_S_M_USE_CB_VOICE_S
WHERE
MONTH_ID = '201801'
GROUP BY
MONTH_ID,DEVICE_NUMBER;


--BSS_M
INSERT INTO
DWA_A_M_PRO_MB_USER

SELECT
A.MONTH_ID,	--月份
A.DEVICE_NUMBER,	--电话号码
A.PROD_IN_LOCAL_FLUX + A.PROD_IN_ROAM_CONT_FLUX + A.PROD_IN_ROAM_GAT_FLUX + A.PROD_IN_ROAM_INT_FLUX AS FLUX_PRO_USED,	--套餐内使用流量
A.FLUX_4G,	--4g基站流量
A.TOTAL_FEE, --超出套餐流量费用
A.BILL_FLUX, --超出主套餐的流量
B.SMS_OUT,	--套餐外短信数量
C.BZ_FEE_FLUX,	--标准资费流量
B.SEND_SMS_NUM,	--发送短信数
D.VOICE_OUT,	--使用套外语音分钟数
D.CALL_TIMES,	--通话次数
D.CALLING_TIMES,	--主叫通话时长
F.SEND_MMS_NUM,	--发送彩信数
G.lac_id,	--常住基站lac
G.cell_id,	--常住基站cell_id
H.roam_day,	--漫游天数
I.ACTIVE_BS_NUM,	--使用活跃基站数
FROM
DWA.DWA_V_M_CUS_MB_SING_FLUX A
LEFT OUTER JOIN
(select MONTH_ID,DEVICE_NUMBER,sum(CASE WHEN TOTAL_FEE > 0 THEN CDR_NUM ELSE 0 END) AS SMS_OUT,
SUM(CDR_NUM) AS SEND_SMS_NUM 
from dwa.DWA_S_M_USE_MB_SMS where TOTAL_FEE > 0 AND SMS_DIRECT = '01' GROUP BY MONTH_ID,DEVICE_NUMBER) B
ON
A.DEVICE_NUMBER = B.DEVICE_NUMBER
AND A.MONTH_ID = B.MONTH_ID
LEFT OUTER JOIN
(select MONTH_ID,DEVICE_NUMBER,sum(total_bytes) AS BZ_FEE_FLUX from dwa.DWA_S_M_USE_MB_FLUX where stream_type=1 GROUP BY MONTH_ID,DEVICE_NUMBER) C
ON
A.DEVICE_NUMBER = C.DEVICE_NUMBER
AND A.MONTH_ID = C.MONTH_ID
LEFT OUTER JOIN
MID_M_CB_VOICE_S D
ON
A.DEVICE_NUMBER = D.DEVICE_NUMBER
AND A.MONTH_ID = D.MONTH_ID
LEFT OUTER JOIN
(select MONTH_ID,DEVICE_NUMBER,count(*) AS CALL_10010 from dwd.DWD_D_USE_MB_VOICE where OPPOSE_NUMBER = '10010' GROUP BY MONTH_ID,DEVICE_NUMBER) E
ON
A.MONTH_ID = E.MONTH_ID
AND A.DEVICE_NUMBER = E.DEVICE_NUMBER
LEFT OUTER JOIN
(select MONTH_ID,DEVICE_NUMBER,count(*) AS SEND_MMS_NUM from dwd.DWD_D_USE_MB_MMS where SMS_DIRECT='01' GROUP BY MONTH_ID, DEVICE_NUMBER) F
ON
A.MONTH_ID = F.MONTH_ID
AND A.DEVICE_NUMBER = F.DEVICE_NUMBER
LEFT OUTER JOIN
of_dwa.dwa_v_m_bs_place G
ON
A.MONTH_ID = G.MONTH_ID
AND A.DEVICE_NUMBER = G.DEVICE_NUMBER
LEFT OUTER JOIN
(select month_id,DEVICE_NUMBER,count(distinct day_id) as roam_day from (select month_id,day_id,roam_type,DEVICE_NUMBER,count(*) as roam_bs_num from dwa.DWA_S_D_USE_MB_BS where roam_type <> '01AA' group by month_id,day_id,roam_type,DEVICE_NUMBER) T_A where roam_bs_num > 0 group by month_id,DEVICE_NUMBER) H
ON
A.MONTH_ID = H.MONTH_ID
AND A.DEVICE_NUMBER = H.DEVICE_NUMBER
LEFT OUTER JOIN
(select MONTH_ID,DEVICE_NUMBER,count(*) as ACTIVE_BS_NUM from 
(select MONTH_ID,DEVICE_NUMBER,lac_id,cell_id,sum(FLUX_UP + FLUX_DOWN) AS FLUX,sum(call_times) AS CALL_TIMES from dwa.DWA_S_D_USE_MB_BS 
group by MONTH_ID,DEVICE_NUMBER,lac_id,cell_id) T_B
where FLUX >= 1024 AND CALL_TIMES > 0
group by MONTH_ID,DEVICE_NUMBER) I
ON
A.MONTH_ID = I.MONTH_ID
AND A.DEVICE_NUMBER = I.DEVICE_NUMBER
WHERE
A.MONTH_ID = '201801'
AND A.DEVICE_NUMBER = '15577111325';


--BSS_D
INSERT INTO
DWA_A_D_PRO_MB_USER

SELECT
A.PROD_IN_LOCAL_FLUX + A.PROD_IN_ROAM_CONT_FLUX + A.PROD_IN_ROAM_GAT_FLUX + A.PROD_IN_ROAM_INT_FLUX AS FLUX_PRO_USED,	--套餐内使用流量
A.UP_ROAM_PROV_FLUX + A.DOWN_ROAM_PROV_FLUX as ROAM_PROV_FLUX, --省内漫游流量
A.FLUX_4G,	--4G基站流量
A.DOWN_ROAM_INT_FLUX + A.UP_ROAM_INT_FLUX AS ROAM_INT_FLUX, --国际漫游流量
A.UP_LOCAL_FLUX + A.DOWN_LOCAL_FLUX AS LOCAL_FLUX,	--本地使用流量
A.BILL_FLUX, --超出主套餐的流量
B.SMS_OUT,	--套餐外短信
B.SEND_SMS_NUM,	--发送短信数
C.BZ_FEE_FLUX,	--标准资费流量
D.VOICE_OUT,	--套外分钟数
E.SEND_MMS_NUM,	--发送彩信数
F.ROAM_BS_NUM,	--漫游基站数
I.ACTIVE_BS_NUM,	--使用活跃基站数
FROM
DWA.DWA_V_D_CUS_MB_SING_FLUX A
LEFT OUTER JOIN
(select MONTH_ID,DAY_ID,DEVICE_NUMBER,sum(CASE WHEN TOTAL_FEE > 0 THEN CDR_NUM ELSE 0 END) AS SMS_OUT,
SUM(CDR_NUM) AS SEND_SMS_NUM 
from dwa.DWA_S_D_USE_MB_SMS where TOTAL_FEE > 0 AND SMS_DIRECT = '01' GROUP BY MONTH_ID,DAY_ID,DEVICE_NUMBER) B
ON
A.DEVICE_NUMBER = B.DEVICE_NUMBER
AND A.MONTH_ID = B.MONTH_ID
AND A.DAY_ID = B.DAY_ID
LEFT OUTER JOIN
(select MONTH_ID,DAY_ID,DEVICE_NUMBER,sum(total_bytes) AS BZ_FEE_FLUX from dwa.DWA_S_D_USE_MB_FLUX where stream_type=1 GROUP BY MONTH_ID,DAY_ID,DEVICE_NUMBER) C
ON
A.DEVICE_NUMBER = C.DEVICE_NUMBER
AND A.MONTH_ID = C.MONTH_ID
AND A.DAY_ID = C.DAY_ID
LEFT OUTER JOIN
(select MONTH_ID,DAY_ID,DEVICE_NUMBER,sum(CALL_DURATION) / 60 AS VOICE_OUT from dwa.DWA_S_D_USE_MB_VOICE_S where total_fee > 0 GROUP BY MONTH_ID,DAY_ID,DEVICE_NUMBER) D
ON
A.DEVICE_NUMBER = D.DEVICE_NUMBER
AND A.MONTH_ID = D.MONTH_ID
AND A.DAY_ID = D.DAY_ID
LEFT OUTER JOIN
(select MONTH_ID,DAY_ID,DEVICE_NUMBER,count(*) AS SEND_MMS_NUM from dwd.DWD_D_USE_MB_MMS where SMS_DIRECT='01' GROUP BY MONTH_ID,DAY_ID,DEVICE_NUMBER) E
ON
A.MONTH_ID = E.MONTH_ID
AND A.DEVICE_NUMBER = E.DEVICE_NUMBER
AND A.DAY_ID = E.DAY_ID
LEFT OUTER JOIN
(select MONTH_ID,DEVICE_NUMBER,count(distinct lac_id, cell_id) AS ROAM_BS_NUM from dwa.DWA_S_D_USE_MB_BS where roam_type <> '01AA' AND DAY_ID < '06' GROUP BY MONTH_ID,DEVICE_NUMBER) F
ON
A.MONTH_ID = F.MONTH_ID
AND A.DEVICE_NUMBER = F.DEVICE_NUMBER
LEFT OUTER JOIN
(select MONTH_ID,DAY_ID,DEVICE_NUMBER,count(*) as ACTIVE_BS_NUM from 
(select MONTH_ID,DAY_ID,DEVICE_NUMBER,lac_id,cell_id,sum(FLUX_UP + FLUX_DOWN) AS FLUX,sum(call_times) AS CALL_TIMES from dwa.DWA_S_D_USE_MB_BS 
group by MONTH_ID,DAY_ID,DEVICE_NUMBER,lac_id,cell_id) T_B
where FLUX >= 1024 AND CALL_TIMES > 0
group by MONTH_ID,DAY_ID,DEVICE_NUMBER) I
ON
A.MONTH_ID = I.MONTH_ID
AND A.DAY_ID = I.DAY_ID
AND A.DEVICE_NUMBER = I.DEVICE_NUMBER
WHERE
A.MONTH_ID = '201802'
AND A.DAY_ID = '06'
AND A.DEVICE_NUMBER = '15577111325';


--CB_M
INSERT INTO
DWA_A_M_PRO_MB_USER

SELECT
A.MONTH_ID,	--月份
A.DEVICE_NUMBER,	--电话号码
A.PROD_IN_LOCAL_FLUX + A.PROD_IN_ROAM_CONT_FLUX + A.PROD_IN_ROAM_GAT_FLUX + A.PROD_IN_ROAM_INT_FLUX AS FLUX_PRO_USED,	--套餐内使用流量
A.FLUX_4G,	--4g基站流量
A.TOTAL_FEE, --超出套餐流量费用
A.BILL_FLUX, --超出主套餐的流量
B.SMS_OUT,	--套餐外短信数量
C.BZ_FEE_FLUX,	--标准资费流量
B.SEND_SMS_NUM,	--发送短信数
D.VOICE_OUT,	--使用套外语音分钟数
D.CALL_TIMES,	--通话次数
D.CALLING_TIMES,	--主叫通话时长
F.lac_id,	--常驻基站lac
F.cell_id,	--常住基站cell_id
G.roam_day,	--漫游天数
FROM
DWA.DWA_V_M_CUS_CB_SING_FLUX A
LEFT OUTER JOIN
(select MONTH_ID,DEVICE_NUMBER,sum(CASE WHEN TOTAL_FEE > 0 THEN CDR_NUM ELSE 0 END) AS SMS_OUT,
SUM(CDR_NUM) AS SEND_SMS_NUM 
from dwa.DWA_S_M_USE_CB_SMS where TOTAL_FEE > 0 AND SMS_DIRECT = '01' GROUP BY MONTH_ID,DEVICE_NUMBER) B
ON
A.DEVICE_NUMBER = B.DEVICE_NUMBER
AND A.MONTH_ID = B.MONTH_ID
LEFT OUTER JOIN
(select MONTH_ID,DEVICE_NUMBER,sum(total_bytes) AS BZ_FEE_FLUX from dwa.DWA_S_D_USE_CB_FLUX where TOTAL_FEE=BEF_BASE_FEE GROUP BY MONTH_ID,DEVICE_NUMBER) C
ON
A.DEVICE_NUMBER = C.DEVICE_NUMBER
AND A.MONTH_ID = C.MONTH_ID
LEFT OUTER JOIN
MID_M_CB_VOICE_S D
ON
A.DEVICE_NUMBER = D.DEVICE_NUMBER
AND A.MONTH_ID = D.MONTH_ID
LEFT OUTER JOIN
(select MONTH_ID,DEVICE_NUMBER,count(*) AS CALL_10010 from dwd.DWD_D_USE_CB_VOICE where OPPOSE_NUMBER = '10010' GROUP BY MONTH_ID,DEVICE_NUMBER) E
ON
A.MONTH_ID = E.MONTH_ID
AND A.DEVICE_NUMBER = E.DEVICE_NUMBER
LEFT OUTER JOIN
of_dwa.dwa_v_m_bs_place F
ON
A.MONTH_ID = F.MONTH_ID
AND A.DEVICE_NUMBER = F.DEVICE_NUMBER
LEFT OUTER JOIN
(select month_id,DEVICE_NUMBER,count(distinct day_id) as roam_day from (select month_id,day_id,roam_type,DEVICE_NUMBER,count(*) as roam_bs_num from dwa.DWA_S_D_USE_CB_BS where roam_type <> '01AA' group by month_id,day_id,roam_type,DEVICE_NUMBER) T_A where roam_bs_num > 0 group by month_id,DEVICE_NUMBER) G
ON
A.MONTH_ID = G.MONTH_ID
AND A.DEVICE_NUMBER = G.DEVICE_NUMBER
LEFT OUTER JOIN
(select MONTH_ID,DEVICE_NUMBER,count(*) as ACTIVE_BS_NUM from (select MONTH_ID,DEVICE_NUMBER,lac,cell_id,sum(FLUX_UP + FLUX_DOWN) AS FLUX,sum(case when CALL_DURATION > 0 then 1 else 0 end) > 0 AS CALL_TIMES from dwd.DWD_D_USE_CB_FLUX  group by MONTH_ID,DEVICE_NUMBER,lac,cell_id) a where A.FLUX >= 1024 OR A.CALL_TIMES > 0 GROUP BY MONTH_ID,DEVICE_NUMBER) H
ON
A.MONTH_ID = H.MONTH_ID
AND A.DEVICE_NUMBER = H.DEVICE_NUMBER
WHERE
A.MONTH_ID = '201801'
AND A.DEVICE_NUMBER = '15577111325';

--CB_D
INSERT INTO
DWA_A_D_PRO_MB_USER

SELECT
A.PROD_IN_LOCAL_FLUX + A.PROD_IN_ROAM_CONT_FLUX + A.PROD_IN_ROAM_GAT_FLUX + A.PROD_IN_ROAM_INT_FLUX AS FLUX_PRO_USED,	--套餐内使用流量
A.UP_ROAM_PROV_FLUX + A.DOWN_ROAM_PROV_FLUX as ROAM_PROV_FLUX, --省内漫游流量
A.FLUX_4G,	--4G基站流量
A.DOWN_ROAM_INT_FLUX + A.UP_ROAM_INT_FLUX AS ROAM_INT_FLUX, --国际漫游流量
A.UP_LOCAL_FLUX + A.DOWN_LOCAL_FLUX AS LOCAL_FLUX,	--本地使用流量
A.BILL_FLUX, --超出主套餐的流量
B.SMS_OUT,	--套餐外短信
C.BZ_FEE_FLUX,	--标准资费流量
B.SEND_SMS_NUM,	--发送短信数
D.VOICE_OUT,	--使用套外语音分钟数
E.roam_bs_num,	--漫游基站数
F.ACTIVE_BS_NUM,	--活跃基站数
FROM
DWA.DWA_V_D_CUS_CB_SING_FLUX A
LEFT OUTER JOIN
(select MONTH_ID,DAY_ID,DEVICE_NUMBER,sum(CASE WHEN TOTAL_FEE > 0 THEN CDR_NUM ELSE 0 END) AS SMS_OUT,
SUM(CDR_NUM) AS SEND_SMS_NUM 
from dwa.DWA_S_D_USE_CB_SMS where TOTAL_FEE > 0 AND SMS_DIRECT = '01' GROUP BY MONTH_ID,DAY_ID,DEVICE_NUMBER) B
ON
A.DEVICE_NUMBER = B.DEVICE_NUMBER
AND A.MONTH_ID = B.MONTH_ID
AND A.DAY_ID = B.DAY_ID
LEFT OUTER JOIN
(select MONTH_ID,DAY_ID,DEVICE_NUMBER,sum(total_bytes) AS BZ_FEE_FLUX from dwa.DWA_S_D_USE_CB_FLUX where TOTAL_FEE=BEF_BASE_FEE GROUP BY MONTH_ID,DAY_ID,DEVICE_NUMBER) C
ON
A.DEVICE_NUMBER = C.DEVICE_NUMBER
AND A.MONTH_ID = C.MONTH_ID
AND A.DAY_ID = C.DAY_ID
LEFT OUTER JOIN
(select MONTH_ID,DAY_ID,DEVICE_NUMBER,sum(CALL_DURATION) / 60 AS VOICE_OUT from dwa.DWA_S_D_USE_CB_VOICE_S where total_fee > 0 GROUP BY MONTH_ID,DAY_ID,DEVICE_NUMBER) D
ON
A.DEVICE_NUMBER = D.DEVICE_NUMBER
AND A.MONTH_ID = D.MONTH_ID
AND A.DAY_ID = D.DAY_ID
LEFT OUTER JOIN
(select MONTH_ID,DEVICE_NUMBER,count(distinct lac, cell_id) AS roam_bs_num from dwd.DWD_D_USE_CB_FLUX where day_id <= '06' and roam_type_cbss <> '0' GROUP BY MONTH_ID, DEVICE_NUMBER) E
ON
A.DEVICE_NUMBER = E.DEVICE_NUMBER
AND A.MONTH_ID = E.MONTH_ID
LEFT OUTER JOIN
(select MONTH_ID,DAY_ID,DEVICE_NUMBER,count(*) as ACTIVE_BS_NUM from (select MONTH_ID,DAY_ID,DEVICE_NUMBER,lac,cell_id,sum(FLUX_UP + FLUX_DOWN) AS FLUX,sum(case when CALL_DURATION > 0 then 1 else 0 end) > 0 AS CALL_TIMES from dwd.DWD_D_USE_CB_FLUX  group by MONTH_ID,DAY_ID,DEVICE_NUMBER,lac,cell_id) a where A.FLUX >= 1024 OR A.CALL_TIMES > 0 GROUP BY MONTH_ID,DAY_ID,DEVICE_NUMBER) F
ON
A.MONTH_ID = F.MONTH_ID
AND A.DAY_ID = F.DAY_ID
AND A.DEVICE_NUMBER = F.DEVICE_NUMBER
WHERE
A.MONTH_ID = '201802'
AND A.DAY_ID = '06'
AND A.DEVICE_NUMBER = '15577111325';
